(function () {
  const S=window.TamakoSettings,State=window.TamakoState,Quiz=window.TamakoQuiz,Audio=window.TamakoAudio,Stickers=window.TamakoStickers,Support=window.TamakoSupportStamps,SupportVoice=window.TamakoSupportVoice;
  let words=[],state=null,selectedCat=S.ALL_CATEGORY_VALUE,session=null,timerId=null,advanceTimer=null,encouragementTimer=null,encouragementBusy=false,scoreViewLevel=1;
  const TTS_ENDPOINT="/api/tts/encouragement";
  const VOICE_BASE="assets/voices/encouragement/";
  function voiceMessage(name,text){return Object.freeze({text,sources:[VOICE_BASE+name+".webm",VOICE_BASE+name+".mp3"]});}
  const finishMessages=Object.freeze([voiceMessage("finish-01","きょうもできたね"),voiceMessage("finish-02","よくがんばったね"),voiceMessage("finish-03","さいごまでできたね"),voiceMessage("finish-04","またやろうね"),voiceMessage("finish-05","いいちょうしだね"),voiceMessage("finish-06","すごいね"),voiceMessage("finish-07","えらかったね"),voiceMessage("finish-08","ひとつずつできてるよ"),voiceMessage("finish-09","つづけていてすごいね"),voiceMessage("finish-10","きょうもありがとう")]);
  const reviewCompleteMessages=Object.freeze([voiceMessage("review-01","ふくしゅうできたね"),voiceMessage("review-02","よくおぼえていたね"),voiceMessage("review-03","もういちどできてすごいね"),voiceMessage("review-04","だいじょうぶ、できてるよ"),voiceMessage("review-05","またいっしょにやろうね")]);
  const ENCOURAGEMENTS=Object.freeze({finish:finishMessages,reviewComplete:reviewCompleteMessages});
  const missingEncouragementAudio=new Set();
  const el={};
  document.addEventListener("DOMContentLoaded",init);
  async function init(){cacheElements();state=State.loadState();selectedCat=state.selectedCat||S.ALL_CATEGORY_VALUE;scoreViewLevel=state.currentLevel||1;bind();try{words=await loadVocabulary();enableMainButtons(true);if(el.loadStatus)el.loadStatus.classList.add("hide");if("speechSynthesis"in window)window.speechSynthesis.onvoiceschanged=()=>{};updateStart();}catch(error){showLoadError(error);}}
  function cacheElements(){["startScreen","gameScreen","resultScreen","scoreScreen","stickerScreen","settingsScreen","feedback","levelStatus","levelSub","progressBar","progressPercent","loadStatus","startBtn","toggleCatBtn","reviewBtn","scoreBtn","stickerBtn","settingsBtn","catStatus","catPanel","catBtns","randomBtn","qCount","timer","currentLevel","wordCard","kanaText","wordText","listenBtn","choices","quitBtn","levelUpMsg","finalScore","resultMsg","earnedStickerWrap","earnedSticker","stickerMsg","againBtn","homeBtn","levelTabs","scoreList","scoreHomeBtn","stickerCount","stickerGrid","stickerHomeBtn","pronunciationOptions","timeOptions","questionOptions","supportPhotoInput","supportStampPreview","supportDeleteBtn","supportStampStatus","supportVoiceMount","settingsHomeBtn","fbWordImage","fbCircle","fbEmoji","fbText","fbAnswer","fbAnswerSmall"].forEach((id)=>{el[id]=document.getElementById(id);});}
  async function loadVocabulary(){const fallback=Array.isArray(window.TAMAKO_WORDS_EN)?window.TAMAKO_WORDS_EN:[];if(window.location.protocol!=="file:"){try{const response=await fetch("./src/data/words_en.json",{cache:"no-cache"});if(response.ok)return Quiz.normalizeVocabulary(await response.json());}catch(error){console.warn("words_en.json fetch failed, using script fallback",error);}}const normalized=Quiz.normalizeVocabulary(fallback);if(!normalized.length)throw new Error("ことばデータをよみこめません");return normalized;}
  function showLoadError(error){console.error("app init failed",error);enableMainButtons(false);if(el.loadStatus){el.loadStatus.className="errorBox";el.loadStatus.textContent="ことばをよみこめません。ローカルHTTPサーバーでひらいてください。";}}
  function enableMainButtons(enabled){[el.startBtn,el.toggleCatBtn,el.reviewBtn,el.scoreBtn,el.stickerBtn,el.settingsBtn].forEach((button)=>{if(button)button.disabled=!enabled;});}
  function save(){State.saveState(state,selectedCat);}
  function getSettings(){state.settings=State.normalizeSettings(state.settings);return state.settings;}
  function maxQuestions(){return Number(getSettings().questionCount||S.DEFAULT_SETTINGS.questionCount);}
  function currentTimeLimit(){const limit=getSettings().timeLimit;return Number(limit===undefined?S.DEFAULT_SETTINGS.timeLimit:limit);}
  function supportVoiceUsage(){state.supportVoiceUsage=State.normalizeSupportVoiceUsage(state.supportVoiceUsage);return state.supportVoiceUsage;}
  function clearEncouragementTimer(){if(encouragementTimer){window.clearTimeout(encouragementTimer);encouragementTimer=null;}}
  function speakEncouragementText(item){if(Audio&&Audio.speak)Audio.speak(item.text,Object.assign({},getSettings(),{pronunciation:"kana"}));}
  async function playWorkerEncouragementAudio(item,type){let url="";try{const response=await fetch(TTS_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","Accept":"audio/mpeg"},body:JSON.stringify({type,text:item.text})});if(!response.ok)return false;const contentType=response.headers.get("content-type")||"";if(!contentType.includes("audio/"))return false;const blob=await response.blob();if(!blob.size)return false;url=URL.createObjectURL(blob);const audio=new window.Audio(url);audio.onended=()=>URL.revokeObjectURL(url);audio.onerror=()=>URL.revokeObjectURL(url);await audio.play();return true;}catch(error){if(url)URL.revokeObjectURL(url);return false;}}
  async function playEncouragementAudio(item){const sources=item.sources||[];for(const source of sources){if(missingEncouragementAudio.has(source))continue;let url="";try{const response=await fetch(source,{cache:"force-cache"});if(!response.ok){missingEncouragementAudio.add(source);continue;}const blob=await response.blob();url=URL.createObjectURL(blob);const audio=new window.Audio(url);audio.onended=()=>URL.revokeObjectURL(url);audio.onerror=()=>URL.revokeObjectURL(url);await audio.play();return true;}catch(error){if(url)URL.revokeObjectURL(url);else missingEncouragementAudio.add(source);}}return false;}
  function playEncouragement(type,delay){clearEncouragementTimer();if(!supportVoiceUsage().encouragement)return;const list=ENCOURAGEMENTS[type]||[];if(!list.length)return;const item=list[Math.floor(Math.random()*list.length)];const play=()=>{encouragementTimer=null;if(encouragementBusy)return;encouragementBusy=true;playWorkerEncouragementAudio(item,type).then((ok)=>ok||playEncouragementAudio(item)).then((ok)=>{if(!ok)speakEncouragementText(item);}).finally(()=>{encouragementBusy=false;});};if(delay>0){encouragementTimer=window.setTimeout(play,delay);return;}play();}
  function updateStart(){const levelChange=Quiz.checkLevelUp(words,state);if(levelChange.leveled)selectedCat=S.ALL_CATEGORY_VALUE;selectedCat=Quiz.ensureCategory(words,state,selectedCat);const level=state.currentLevel;const percent=Math.floor(Quiz.rate(words,state,level)*100);el.levelStatus.textContent="レベル"+level;el.levelSub.textContent=S.LEVEL_LABELS[level]||"";el.progressBar.style.width=percent+"%";el.progressPercent.textContent=percent+"%";el.catStatus.textContent=selectedCat===S.ALL_CATEGORY_VALUE?"いまは ぜんぶ":"いまは "+selectedCat;el.reviewBtn.classList.toggle("hide",!Quiz.hasReview(words,state));makeCategoryButtons();save();}
  function show(screenId){if(screenId!=="gameScreen"){endTimer();clearAdvanceTimer();clearEncouragementTimer();}document.querySelectorAll(".screen").forEach((screen)=>screen.classList.remove("active"));document.getElementById(screenId).classList.add("active");if(screenId==="startScreen")updateStart();}
  function makeCategoryButtons(){selectedCat=Quiz.ensureCategory(words,state,selectedCat);el.catBtns.innerHTML="";Quiz.availableCategories(words,state).forEach((category)=>{const button=document.createElement("button");button.className="btn small "+(category===selectedCat?"selected":"");button.type="button";button.textContent=category;button.onclick=()=>{selectedCat=category;save();updateStart();el.catPanel.classList.add("hide");};el.catBtns.appendChild(button);});}
  function renderSettings(){const settings=getSettings();const make=(box,options,key)=>{if(!box)return;box.innerHTML="";options.forEach((option)=>{const selected=String(settings[key])===String(option.value);const button=document.createElement("button");button.className="btn settingOption"+(selected?" selectedSetting":"");button.type="button";button.innerHTML=`<span class="mark">${selected?"◎":"○"}</span><span>${option.label}</span>`;button.onclick=()=>{getSettings()[key]=option.value;save();renderSettings();};box.appendChild(button);});};make(el.pronunciationOptions,S.PRONUNCIATION_OPTIONS,"pronunciation");make(el.timeOptions,S.TIME_OPTIONS,"timeLimit");make(el.questionOptions,S.QUESTION_OPTIONS,"questionCount");renderSupportStampSettings("");renderSupportVoiceSettings();}
  function renderSupportVoiceSettings(){if(el.supportVoiceMount&&SupportVoice)SupportVoice.render(el.supportVoiceMount,state,{onSave:save});}
  function renderSupportStampSettings(message){if(!el.supportStampPreview||!Support)return;state.supportStamp=State.normalizeSupportStamp(state.supportStamp);el.supportStampPreview.innerHTML="";if(Support.hasPhoto(state)){const stamp=Support.createStampElement(state,{preview:true});if(stamp)el.supportStampPreview.appendChild(stamp);if(el.supportDeleteBtn){el.supportDeleteBtn.disabled=false;el.supportDeleteBtn.classList.remove("disabledBtn");}}else{const empty=document.createElement("div");empty.className="supportEmptyPreview";empty.textContent="しゃしんはまだありません";el.supportStampPreview.appendChild(empty);if(el.supportDeleteBtn){el.supportDeleteBtn.disabled=true;el.supportDeleteBtn.classList.add("disabledBtn");}}setSupportStatus(message||"");}
  function setSupportStatus(text){if(el.supportStampStatus)el.supportStampStatus.textContent=text||"";}
  async function handleSupportPhotoChange(){if(!Support||!el.supportPhotoInput)return;const file=el.supportPhotoInput.files&&el.supportPhotoInput.files[0];if(!file)return;const previous=State.normalizeSupportStamp(state.supportStamp);setSupportStatus("しゃしんをよみこみます");try{const stamp=await Support.fromFile(file);state.supportStamp=stamp;save();renderSupportStampSettings("しゃしんをほぞんしました");}catch(error){console.warn("support stamp save failed",error);state.supportStamp=previous;try{save();}catch(saveError){console.warn("support stamp rollback failed",saveError);}renderSupportStampSettings("しゃしんをほぞんできませんでした");}el.supportPhotoInput.value="";}
  function deleteSupportPhoto(){if(!Support)return;state.supportStamp=Support.empty();try{save();state=State.loadState();selectedCat=state.selectedCat||selectedCat;renderSupportStampSettings("しゃしんをけしました");if(el.stickerScreen&&el.stickerScreen.classList.contains("active"))renderStickers();}catch(error){console.warn("support stamp delete failed",error);renderSupportStampSettings("けすことができませんでした");}}
  function bind(){el.startBtn.onclick=()=>{Audio.prepare("./assets/pinpon.wav");startGame("normal");};el.reviewBtn.onclick=()=>{Audio.prepare("./assets/pinpon.wav");startGame("review");};el.toggleCatBtn.onclick=()=>el.catPanel.classList.toggle("hide");el.randomBtn.onclick=()=>{selectedCat=S.ALL_CATEGORY_VALUE;save();updateStart();el.catPanel.classList.add("hide");};el.scoreBtn.onclick=()=>{scoreViewLevel=state.currentLevel;renderScore();show("scoreScreen");};el.stickerBtn.onclick=()=>{show("stickerScreen");renderStickers();};el.listenBtn.onclick=()=>{Audio.prepare("./assets/pinpon.wav");speakCurrent();};el.quitBtn.onclick=()=>show("startScreen");el.againBtn.onclick=()=>startGame(session&&session.mode?session.mode:"normal");el.homeBtn.onclick=()=>show("startScreen");el.scoreHomeBtn.onclick=()=>show("startScreen");el.stickerHomeBtn.onclick=()=>show("startScreen");el.settingsBtn.onclick=()=>{renderSettings();show("settingsScreen");};if(el.supportPhotoInput)el.supportPhotoInput.onchange=handleSupportPhotoChange;if(el.supportDeleteBtn)el.supportDeleteBtn.onclick=deleteSupportPhoto;el.settingsHomeBtn.onclick=()=>show("startScreen");}
  function startGame(mode){endTimer();clearAdvanceTimer();clearEncouragementTimer();updateStart();const questions=Quiz.makeQuestionList(words,state,selectedCat,mode,maxQuestions());if(!questions.length){noQuestion(mode);return;}session={mode,index:0,correct:0,current:null,answered:false,finished:false,questions,total:questions.length,levelAtStart:state.currentLevel};show("gameScreen");renderQuestion();}
  function noQuestion(mode){clearFeedbackWordImage();el.feedback.classList.remove("simpleFeedback");el.fbCircle.textContent="🌱";el.fbCircle.style.color="var(--pink)";el.fbEmoji.textContent="";el.fbText.textContent=mode==="review"?"ふくしゅうは ないよ":"ことばが ないよ";el.fbAnswer.textContent=mode==="review"?"よくおぼえてるね":"ぜんぶにもどします";el.fbAnswerSmall.textContent="";el.feedback.classList.add("show");window.setTimeout(()=>{el.feedback.classList.remove("show");selectedCat=S.ALL_CATEGORY_VALUE;show("startScreen");},1500);}
  function renderQuestion(){endTimer();clearAdvanceTimer();if(!session||session.finished)return;if(session.index>=session.total){finishGame();return;}const question=session.questions[session.index];if(!question){finishGame();return;}session.current=question;session.answered=false;el.qCount.textContent=session.index+1+" / "+session.total;el.currentLevel.textContent=session.mode==="review"?"ふくしゅう":"レベル"+state.currentLevel;el.kanaText.textContent=question.reading;el.wordText.textContent=question.promptText;el.choices.innerHTML="";Quiz.makeChoices(words,question).forEach((answerText)=>{const button=document.createElement("button");button.className="btn choice";button.type="button";button.textContent=answerText;button.onclick=()=>answer(answerText===question.answerText);el.choices.appendChild(button);});speakCurrent();startTimer();}
  function cardImageAlt(question){const label=[question.promptText,question.answerText].filter(Boolean).join("、");return question.imageAlt||`${label}のえカード`;}
  function speakCurrent(){if(session&&session.current)Audio.speakWord(session.current,getSettings());}
  function startTimer(){const limit=currentTimeLimit();if(limit<=0){el.timer.textContent="なし";return;}let left=limit;el.timer.textContent=left;timerId=window.setInterval(()=>{left-=1;el.timer.textContent=left;if(left<=0){endTimer();answer(false);}},1000);}
  function endTimer(){if(timerId){window.clearInterval(timerId);timerId=null;}}
  function clearAdvanceTimer(){if(advanceTimer){window.clearTimeout(advanceTimer);advanceTimer=null;}}
  function scheduleAdvance(fn,ms){clearAdvanceTimer();advanceTimer=window.setTimeout(()=>{advanceTimer=null;fn();},ms);}
  function answer(ok){if(!session||session.finished||session.answered)return;session.answered=true;endTimer();clearAdvanceTimer();document.querySelectorAll("#choices .choice").forEach((button)=>{button.disabled=true;});const question=session.current;if(!question){finishGame();return;}const stat=State.wordStat(state,question);stat.seen+=1;if(ok){stat.correct+=1;stat.streak=(stat.streak||0)+1;if(stat.streak>=S.LEARN_STREAK)stat.learned=true;session.correct+=1;showFeedback(true,question);Audio.playPinpon(getSettings());}else{stat.wrong+=1;stat.streak=0;if(!stat.learned)stat.learned=false;showFeedback(false,question);}save();const wasLast=session.index+1>=session.total;const wait=ok?1100:2600;session.index+=1;if(wasLast){scheduleAdvance(()=>{if(session&&!session.finished)finishGame();},wait);return;}if(ok&&session.index%5===0){scheduleAdvance(()=>{if(!session||session.finished)return;showPraise();scheduleAdvance(()=>{if(session&&!session.finished)renderQuestion();},850);},1000);}else{scheduleAdvance(()=>{if(session&&!session.finished)renderQuestion();},wait);}}
  function clearFeedbackWordImage(){if(el.fbWordImage){el.fbWordImage.innerHTML="";el.fbWordImage.classList.add("hide");}if(el.feedback)el.feedback.classList.remove("hasWordImage");}
  function renderFeedbackWordImage(question){clearFeedbackWordImage();if(!el.fbWordImage)return;const imagePath=String(question&&question.cardImage||"");if(!imagePath)return;const img=document.createElement("img");img.src=imagePath;img.alt=cardImageAlt(question);img.decoding="async";img.onload=()=>{el.fbWordImage.classList.remove("hide");if(el.feedback)el.feedback.classList.add("hasWordImage");};img.onerror=()=>clearFeedbackWordImage();el.fbWordImage.appendChild(img);}
  function showPraise(){clearFeedbackWordImage();el.feedback.classList.remove("simpleFeedback");el.fbCircle.textContent="🌸";el.fbCircle.style.color="var(--pink)";el.fbEmoji.textContent="";el.fbText.textContent="いいね";el.fbAnswer.textContent="そのちょうし";el.fbAnswerSmall.textContent="";el.feedback.classList.add("show");window.setTimeout(()=>el.feedback.classList.remove("show"),750);}
  function feedbackSubText(question){const prompt=String(question.promptText||"");const answer=String(question.answerText||"");return prompt&&prompt!==answer?prompt:"";}
  function showFeedback(ok,question){renderFeedbackWordImage(question);el.feedback.classList.add("simpleFeedback");el.fbCircle.textContent=ok?"○":"×";el.fbCircle.style.color=ok?"var(--pink)":"var(--blue)";el.fbEmoji.textContent="";el.fbText.textContent=question.answerText;el.fbAnswer.textContent="";el.fbAnswerSmall.textContent=feedbackSubText(question);el.feedback.classList.add("show");window.setTimeout(()=>el.feedback.classList.remove("show"),ok?950:2400);}
  function renderEarnedSticker(earned,leveled){if(el.earnedStickerWrap&&Support){Support.renderInto(el.earnedStickerWrap,state,{special:leveled,fallbackSrc:Stickers.stickerPath(earned),fallbackAlt:"もらったシール",fallbackClass:"stickerResult",fallbackId:"earnedSticker"});return;}if(el.earnedSticker)el.earnedSticker.src=Stickers.stickerPath(earned);}
  function finishGame(){if(!session||session.finished)return;session.finished=true;endTimer();clearAdvanceTimer();clearEncouragementTimer();const statLevel=session.mode==="review"?session.levelAtStart:state.currentLevel;const levelStats=state.levelStats[statLevel]||{plays:0,reviewPlays:0,best:0,totalCorrect:0};if(session.mode==="review")levelStats.reviewPlays+=1;else levelStats.plays+=1;levelStats.totalCorrect+=session.correct;if(session.correct>(levelStats.best||0))levelStats.best=session.correct;state.levelStats[statLevel]=levelStats;const beforeLevel=state.currentLevel;const levelChange=Quiz.checkLevelUp(words,state);const leveled=levelChange.leveled;let earned="";if(leveled){earned=Stickers.earnLevelUp(state,beforeLevel);selectedCat=S.ALL_CATEGORY_VALUE;el.levelUpMsg.textContent="レベルアップ！";el.resultMsg.textContent="とくべつシール！";}else{earned=Stickers.earnNormal(state);el.levelUpMsg.textContent="";el.resultMsg.textContent="シールをもらったよ";}save();el.finalScore.textContent=session.correct+" / "+session.total;renderEarnedSticker(earned,leveled);el.stickerMsg.textContent=leveled?"とくべつ "+(state.specialStickers||[]).length+"まい":(state.stickers||[]).length+"まい";show("resultScreen");playEncouragement(session.mode==="review"?"reviewComplete":"finish",240);}
  function renderScore(){el.levelTabs.innerHTML="";for(let level=1;level<=S.MAX_LEVEL;level+=1){const button=document.createElement("button");button.className="btn tab "+(level===scoreViewLevel?"selected":"");button.type="button";button.textContent="レベル"+level;button.onclick=()=>{scoreViewLevel=level;renderScore();};el.levelTabs.appendChild(button);}el.scoreList.innerHTML="";const level=scoreViewLevel;const total=Quiz.total(words,level);const learned=Quiz.learnedCount(words,state,level);const levelStats=state.levelStats[level]||{plays:0,reviewPlays:0,best:0,totalCorrect:0};const playCount=levelStats.plays+levelStats.reviewPlays;const average=playCount?Math.round(levelStats.totalCorrect/playCount*10)/10:0;[["レベル",level+"　"+(S.LEVEL_LABELS[level]||"")],["おぼえた",learned+" / "+total],["まだ",total-learned+"こ"],["いちばん",(levelStats.best||0)+" / "+S.MAX_SCORE_DISPLAY],["れんしゅう",(levelStats.plays||0)+"かい"],["ふくしゅう",(levelStats.reviewPlays||0)+"かい"],["へいきん",average+"もん"]].forEach((row)=>{const item=document.createElement("div");item.className="row";item.innerHTML=`<span>${row[0]}</span><span>${row[1]}</span>`;el.scoreList.appendChild(item);});}
  function renderStickers(){try{Stickers.renderStickers(state,{countEl:el.stickerCount,grid:el.stickerGrid});save();}catch(error){console.error("renderStickers error",error);if(el.stickerGrid)el.stickerGrid.innerHTML="<div class='row' style='grid-column:1 / -1;'><span>シールをよみこめません</span><span>⚠️</span></div>";}}
})();

