(function () {
  let pinpon=null;
  let pinponPath="./assets/pinpon.wav";
  function prepare(path){pinponPath=path||pinponPath;if(pinpon)return;try{pinpon=new Audio(pinponPath);pinpon.volume=1;pinpon.preload="auto";pinpon.load();}catch(error){pinpon=null;}}
  function nameOf(voice){return String(voice&&voice.name||"").toLowerCase();}
  function chooseVoice(langPrefix){if(!("speechSynthesis"in window))return null;const voices=window.speechSynthesis.getVoices();const candidates=voices.filter((voice)=>voice.lang&&voice.lang.toLowerCase().startsWith(langPrefix));const femaleWords=["female","woman","girl","samantha","victoria","karen","moira","tessa","fiona","serena","susan","zira","aria","jenny","sonia","natasha","emma","michelle","olivia","ava","allison","joana","sara","monica","nanami","haruka","ayumi","sayaka","kyoko","aoi","mayu","mizuki","naomi"];const maleWords=["male","man","boy","david","daniel","alex","tom","fred","ryan","tony","keita","ichiro","otoya","george","mark"];const isMaleName=(voice)=>{const name=nameOf(voice);if(["female","woman","girl","samantha","victoria","karen","moira","zira","jenny","nanami","haruka","sayaka","kyoko"].some((word)=>name.includes(word)))return false;return maleWords.some((word)=>name.includes(word));};const isFemaleName=(voice)=>femaleWords.some((word)=>nameOf(voice).includes(word))&&!isMaleName(voice);return candidates.find(isFemaleName)||candidates.find((voice)=>!isMaleName(voice))||candidates[0]||null;}
  function speak(text,settings){if(!("speechSynthesis"in window))return;try{window.speechSynthesis.cancel();const isKana=settings.pronunciation==="kana";const utterance=new SpeechSynthesisUtterance(text);const langPrefix=isKana?"ja":"en";utterance.lang=isKana?"ja-JP":"en-US";utterance.rate=isKana?0.78:settings.pronunciation==="slow"?0.65:0.85;utterance.pitch=isKana?1.18:1.1;utterance.volume=1;const voice=chooseVoice(langPrefix);if(voice)utterance.voice=voice;window.speechSynthesis.speak(utterance);}catch(error){console.warn("speech failed",error);}}
  function speakWord(word,settings){const text=settings.pronunciation==="kana"?word.reading:word.audioText;speak(text,settings);}
  function playPinpon(settings){try{if("speechSynthesis"in window)window.speechSynthesis.cancel();}catch(error){}if(pinpon){try{pinpon.pause();pinpon.currentTime=0;const play=pinpon.play();if(play&&play.catch)play.catch(()=>fallback(settings));return;}catch(error){}}fallback(settings);}
  function fallback(settings){try{const AudioCtx=window.AudioContext||window.webkitAudioContext;const ctx=new AudioCtx();[880,1320].forEach((frequency,index)=>{const oscillator=ctx.createOscillator();const gain=ctx.createGain();const start=ctx.currentTime+index*0.15;oscillator.type="sine";oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0.0001,start);gain.gain.exponentialRampToValueAtTime(0.45,start+0.015);gain.gain.exponentialRampToValueAtTime(0.0001,start+0.12);oscillator.connect(gain).connect(ctx.destination);oscillator.start(start);oscillator.stop(start+0.13);});}catch(error){speak("ピンポン",settings||{pronunciation:"kana"});}}
  window.TamakoAudio=Object.freeze({prepare,speak,speakWord,playPinpon});
})();
