(function () {
  const S = window.TamakoSettings;
  function clampLevel(value){const n=Number(value||1);return Math.min(S.MAX_LEVEL,Math.max(1,Number.isFinite(n)?n:1));}
  function normalizeStickers(list){return(Array.isArray(list)?list:[]).map((name)=>String(name).replace(".png",".jpg"));}
  function normalizeSpecialStickers(list){const out=[];normalizeStickers(list).forEach((name)=>{if(!out.includes(name))out.push(name);});return out;}
  function normalizeSupportStamp(input){const prev=input&&typeof input==="object"?input:{};const rawPhoto=typeof prev.photoDataUrl==="string"?prev.photoDataUrl.trim():"";const photo=rawPhoto.indexOf("data:image/")===0?rawPhoto:"";const updatedAt=typeof prev.updatedAt==="string"?prev.updatedAt:"";return{version:1,photoDataUrl:photo,updatedAt};}
  function normalizeSettings(input){const settings=Object.assign({},S.DEFAULT_SETTINGS,input||{});const p=S.PRONUNCIATION_OPTIONS.map((x)=>x.value);const t=S.TIME_OPTIONS.map((x)=>Number(x.value));const q=S.QUESTION_OPTIONS.map((x)=>Number(x.value));if(!p.includes(settings.pronunciation))settings.pronunciation=S.DEFAULT_SETTINGS.pronunciation;settings.timeLimit=Number(settings.timeLimit);if(!t.includes(settings.timeLimit))settings.timeLimit=S.DEFAULT_SETTINGS.timeLimit;settings.questionCount=Number(settings.questionCount);if(!q.includes(settings.questionCount))settings.questionCount=S.DEFAULT_SETTINGS.questionCount;return settings;}
  function normalizeLevelStats(input){const out=input&&typeof input==="object"?input:{};for(let level=1;level<=S.MAX_LEVEL;level+=1){const prev=out[level]||{};out[level]={plays:Number(prev.plays||0),reviewPlays:Number(prev.reviewPlays||0),best:Number(prev.best||0),totalCorrect:Number(prev.totalCorrect||0)};}return out;}
  function normalizeWordStats(input){const out=input&&typeof input==="object"?input:{};Object.keys(out).forEach((key)=>{const prev=out[key]||{};out[key]={seen:Number(prev.seen||0),correct:Number(prev.correct||0),wrong:Number(prev.wrong||0),streak:Number(prev.streak||0),learned:!!prev.learned};});return out;}
  function normalizeState(input){const state=input&&typeof input==="object"?input:{};state.schemaVersion=2;state.currentLevel=clampLevel(state.currentLevel);state.selectedCat=typeof state.selectedCat==="string"&&state.selectedCat?state.selectedCat:S.ALL_CATEGORY_VALUE;if(state.selectedCat==="ぜんぶ")state.selectedCat=S.ALL_CATEGORY_VALUE;state.words=normalizeWordStats(state.words);state.levelStats=normalizeLevelStats(state.levelStats);state.stickers=normalizeStickers(state.stickers);state.specialStickers=normalizeSpecialStickers(state.specialStickers);state.settings=normalizeSettings(state.settings);state.supportStamp=normalizeSupportStamp(state.supportStamp);return state;}
  function loadState(storage){const store=storage||window.localStorage;try{const raw=store.getItem(S.STORAGE_KEY);if(raw)return normalizeState(JSON.parse(raw));}catch(error){console.warn("state load failed",error);}return normalizeState({});}
  function saveState(state,selectedCat,storage){const store=storage||window.localStorage;if(selectedCat!==undefined)state.selectedCat=selectedCat;store.setItem(S.STORAGE_KEY,JSON.stringify(normalizeState(state)));}
  function wordKey(word){return String(word&&(word.legacyKey||word.promptText||word.word||word.id||""));}
  function wordStat(state,word){const key=wordKey(word);if(!state.words[key])state.words[key]={seen:0,correct:0,wrong:0,streak:0,learned:false};return state.words[key];}
  window.TamakoState=Object.freeze({normalizeStickers,normalizeSpecialStickers,normalizeSupportStamp,normalizeSettings,normalizeState,loadState,saveState,wordKey,wordStat});
})();

