(function () {
  const normalStickers=["sticker_01.jpg","sticker_02.jpg","sticker_03.jpg","sticker_04.jpg","sticker_05.jpg","sticker_06.jpg","sticker_07.jpg","sticker_08.jpg","sticker_09.jpg","sticker_10.jpg"];
  const specialStickers={1:"special_level_1.jpg",2:"special_level_2.jpg",3:"special_level_3.jpg",4:"special_level_4.jpg",5:"special_level_5.jpg",6:"special_level_6.jpg"};
  function normalizeName(name){return String(name||"").replace(".png",".jpg");}
  function stickerPath(name){return`./assets/stickers/${normalizeName(name)}`;}
  function randomNormalSticker(){return normalStickers[Math.floor(Math.random()*normalStickers.length)];}
  function earnNormal(state){const earned=randomNormalSticker();state.stickers=state.stickers||[];state.stickers.push(earned);return earned;}
  function earnLevelUp(state,clearedLevel){const earned=specialStickers[String(clearedLevel)]||randomNormalSticker();state.stickers=[];state.specialStickers=window.TamakoState.normalizeSpecialStickers(state.specialStickers||[]);if(!state.specialStickers.includes(earned))state.specialStickers.push(earned);return earned;}
  function renderFallbackImage(cell,name){const img=document.createElement("img");img.src=stickerPath(name);img.alt="シール";img.onerror=()=>{cell.innerHTML="<div style='font-size:20px;font-weight:900;padding:12px;'>画像がありません</div>";};cell.appendChild(img);}
  function renderStickers(state,elements){const grid=elements.grid;const countEl=elements.countEl;if(!grid)return;state.stickers=window.TamakoState.normalizeStickers(state.stickers||[]);state.specialStickers=window.TamakoState.normalizeSpecialStickers(state.specialStickers||[]);state.supportStamp=window.TamakoState.normalizeSupportStamp(state.supportStamp);if(countEl){countEl.textContent="";countEl.classList.add("hide");}grid.innerHTML="";const Support=window.TamakoSupportStamps;const addSticker=(name,specialMode)=>{const cell=document.createElement("div");cell.className="sticker-cell"+(Support&&Support.hasPhoto(state)?" support-sticker-cell":"");if(specialMode){cell.style.gridColumn="1 / -1";cell.style.minHeight="210px";}if(Support&&Support.hasPhoto(state)){cell.appendChild(Support.createStampElement(state,{special:specialMode,compact:!specialMode}));}else{renderFallbackImage(cell,name);}grid.appendChild(cell);};if(state.specialStickers.length===0&&state.stickers.length===0){const empty=document.createElement("div");empty.className="row";empty.style.gridColumn="1 / -1";empty.innerHTML="<span>まだないよ</span><span>🌱</span>";grid.appendChild(empty);return;}state.specialStickers.forEach((name)=>addSticker(name,true));state.stickers.slice(-20).reverse().forEach((name)=>addSticker(name,false));}
  window.TamakoStickers=Object.freeze({normalStickers,specialStickers,stickerPath,earnNormal,earnLevelUp,renderStickers});
})();
