(function () {
  let recorder=null,stream=null,chunks=[],audioUrl="",audioBlob=null,draftMode="",speakerConsent=false,guardianConsent=false,lastMessage="";
  const sampleText="こんにちは。たまこさんのことばトレーニングでつかう、おうえんのこえをろくおんします。";
  function canRecord(){return!!(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&window.MediaRecorder);}
  function stopStream(){if(stream){stream.getTracks().forEach((track)=>track.stop());stream=null;}}
  function revokeAudio(){if(audioUrl){URL.revokeObjectURL(audioUrl);audioUrl="";}audioBlob=null;}
  function profileOf(state){return window.TamakoState.normalizeSupportVoiceProfile(state&&state.supportVoiceProfile);}
  function usageOf(state){return window.TamakoState.normalizeSupportVoiceUsage(state&&state.supportVoiceUsage);}
  function modeOf(state){if(draftMode)return draftMode;return profileOf(state)?"supporter":"device";}
  function setStatus(root,text){const status=root&&root.querySelector("[data-support-voice-status]");if(status)status.textContent=text||"";}
  function saveState(state,onSave){if(onSave)onSave();else if(window.TamakoState)window.TamakoState.saveState(state);}
  function speakSample(state){const Audio=window.TamakoAudio;if(Audio&&Audio.speak)Audio.speak(sampleText,(state&&state.settings)||{pronunciation:"kana"});}
  function preview(state,root){if(audioUrl){const audio=new Audio(audioUrl);const play=audio.play();if(play&&play.catch)play.catch(()=>speakSample(state));return;}speakSample(state);setStatus(root,"たんまつのこえでためします");}
  async function startRecording(root,renderAgain){if(!canRecord()){lastMessage="このブラウザでは録音できません";renderAgain();return;}try{revokeAudio();chunks=[];stream=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(stream);recorder.ondataavailable=(event)=>{if(event.data&&event.data.size)chunks.push(event.data);};recorder.onstop=()=>{audioBlob=new Blob(chunks,{type:recorder&&recorder.mimeType?recorder.mimeType:"audio/webm"});audioUrl=URL.createObjectURL(audioBlob);stopStream();recorder=null;lastMessage="ろくおんできました";renderAgain();};recorder.start();lastMessage="ろくおんしています";renderAgain();}catch(error){console.warn("support voice recording failed",error);stopStream();recorder=null;lastMessage="マイクをつかえませんでした";renderAgain();}}
  function stopRecording(renderAgain){if(recorder&&recorder.state==="recording"){recorder.stop();lastMessage="ろくおんをとめました";renderAgain();return;}stopStream();lastMessage="ろくおんしていません";renderAgain();}
  function saveSupporterVoice(state,onSave,renderAgain){if(!audioBlob&&!profileOf(state)){lastMessage="さきにろくおんしてください";renderAgain();return;}if(!speakerConsent||!guardianConsent){lastMessage="同意チェックをしてください";renderAgain();return;}state.supportVoiceProfile={provider:"elevenlabs",type:"supporter_voice",voiceId:null,status:"recorded_local_only",label:"すきな人のこえ",speakerRole:"guardian",speakerDisplayName:"",speakerConsentChecked:true,guardianConsentChecked:true,createdAt:new Date().toISOString()};state.supportVoiceUsage=usageOf(state);saveState(state,onSave);draftMode="supporter";lastMessage="おうえんのこえをほぞんしました";renderAgain();}
  function deleteSupporterVoice(state,onSave,renderAgain){delete state.supportVoiceProfile;revokeAudio();speakerConsent=false;guardianConsent=false;draftMode="device";saveState(state,onSave);lastMessage="おうえんのこえをけしました";renderAgain();}
  function render(container,state,options){if(!container)return;const opts=options||{};const profile=profileOf(state);const mode=modeOf(state);const usage=usageOf(state);if(profile){speakerConsent=profile.speakerConsentChecked;guardianConsent=profile.guardianConsentChecked;}container.innerHTML="";const root=document.createElement("div");root.className="supportVoiceBox";const title=document.createElement("div");title.className="settingTitle green";title.textContent="おうえんのこえを設定する";root.appendChild(title);const note=document.createElement("div");note.className="supportNote";note.textContent="すきな人のこえで、ことばをよんだり、おうえんしたりできます。録音する人が「いいよ」と言ったときだけ使ってください。";root.appendChild(note);
    const modes=document.createElement("div");modes.className="settingOptions voiceModeOptions";[{value:"device",label:"たんまつのこえ"},{value:"supporter",label:"すきな人のこえ"}].forEach((item)=>{const button=document.createElement("button");button.className="btn settingOption"+(mode===item.value?" selectedSetting":"");button.type="button";button.innerHTML=`<span class="mark">${mode===item.value?"◎":"○"}</span><span>${item.label}</span>`;button.onclick=()=>{draftMode=item.value;if(item.value==="device"){delete state.supportVoiceProfile;saveState(state,opts.onSave);lastMessage="たんまつのこえにしました";}else{lastMessage=profile?"ろくおんずみです":"ろくおんできます";}render(container,state,opts);};modes.appendChild(button);});root.appendChild(modes);
    const usageBox=document.createElement("div");usageBox.className="voiceUsageGrid";[{key:"encouragement",label:"おうえん"},{key:"japaneseWords",label:"日本語"},{key:"englishWords",label:"英語"}].forEach((item)=>{const label=document.createElement("label");label.className="voiceCheck";const input=document.createElement("input");input.type="checkbox";input.checked=!!usage[item.key];input.onchange=()=>{state.supportVoiceUsage=usageOf(state);state.supportVoiceUsage[item.key]=input.checked;saveState(state,opts.onSave);};label.appendChild(input);const span=document.createElement("span");span.textContent=item.label;label.appendChild(span);usageBox.appendChild(label);});root.appendChild(usageBox);
    if(mode==="supporter"){const sample=document.createElement("div");sample.className="voiceSample";sample.textContent="よむ文: しずかなばしょで、はっきりよんでください。";root.appendChild(sample);const actions=document.createElement("div");actions.className="supportActions voiceActions";const recordBtn=document.createElement("button");recordBtn.className="btn blue supportChooseLabel";recordBtn.type="button";recordBtn.disabled=!canRecord()||!!recorder;recordBtn.textContent=recorder?"ろくおん中":"ろくおんする";recordBtn.onclick=()=>startRecording(root,()=>render(container,state,opts));const stopBtn=document.createElement("button");stopBtn.className="btn pink supportDeleteBtn";stopBtn.type="button";stopBtn.disabled=!recorder;stopBtn.textContent="とめる";stopBtn.onclick=()=>stopRecording(()=>render(container,state,opts));actions.appendChild(recordBtn);actions.appendChild(stopBtn);root.appendChild(actions);const previewBtn=document.createElement("button");previewBtn.className="btn green voicePreviewBtn";previewBtn.type="button";previewBtn.disabled=!audioUrl&&!profile;previewBtn.textContent="このこえをきく";previewBtn.onclick=()=>preview(state,root);root.appendChild(previewBtn);[["speaker","ろくおんする人が「いいよ」と言いました"],["guardian","この声を、学習のおうえんだけに使います"]].forEach((item)=>{const label=document.createElement("label");label.className="voiceConsent";const input=document.createElement("input");input.type="checkbox";input.checked=item[0]==="speaker"?speakerConsent:guardianConsent;input.onchange=()=>{if(item[0]==="speaker")speakerConsent=input.checked;else guardianConsent=input.checked;const saveBtn=root.querySelector("[data-support-voice-save]");if(saveBtn)saveBtn.disabled=!(speakerConsent&&guardianConsent&&(audioBlob||profile));};label.appendChild(input);const span=document.createElement("span");span.textContent=item[1];label.appendChild(span);root.appendChild(label);});const saveBtn=document.createElement("button");saveBtn.className="btn yellow voiceSaveBtn";saveBtn.type="button";saveBtn.dataset.supportVoiceSave="1";saveBtn.disabled=!(speakerConsent&&guardianConsent&&(audioBlob||profile));saveBtn.textContent="このこえをつかう";saveBtn.onclick=()=>saveSupporterVoice(state,opts.onSave,()=>render(container,state,opts));root.appendChild(saveBtn);const deleteBtn=document.createElement("button");deleteBtn.className="btn pink voicePreviewBtn";deleteBtn.type="button";deleteBtn.disabled=!profile&&!audioBlob;deleteBtn.textContent="このこえをけす";deleteBtn.onclick=()=>deleteSupporterVoice(state,opts.onSave,()=>render(container,state,opts));root.appendChild(deleteBtn);}else{const previewBtn=document.createElement("button");previewBtn.className="btn green voicePreviewBtn";previewBtn.type="button";previewBtn.textContent="たんまつのこえをきく";previewBtn.onclick=()=>preview(state,root);root.appendChild(previewBtn);}
    const status=document.createElement("div");status.className="supportStatus";status.setAttribute("role","status");status.dataset.supportVoiceStatus="1";status.textContent=lastMessage||(profile?"ろくおんずみです":"");root.appendChild(status);container.appendChild(root);}
  window.TamakoSupportVoice=Object.freeze({render,canRecord,usageOf,profileOf});
})();
